
# Notes {-}

> Articles begin with an unreferenced abstract (typically 150 words) and are
> divided into separate sections for Introduction (without heading), Results,
> Discussion and Methods. The Introduction section should describe the main
> problem being addressed, and is brief and focused; the Results section usually
> contains a general description of the computational technique or mathematical
> model being proposed or used, followed by its validation; the Discussion section
> summarizes the main findings of the research and clearly describes any existing
> limitations; the Methods section provides all technical details necessary for
> the independent reproduction of the results, without referring to a chain of
> bibliographical references. The main text (excluding abstract, Methods,
> references and figure legends) is 2,500–3,500 words. Articles have no more than
> 6 display items (figures and tables). The Results and Methods sections should be
> divided by topical subheadings. As a guideline, Articles allow up to 50
> references.

\newpage
